### ISSUE TITLE
Qt GUI sluggish when loading images

### ISSUE THREAD

**Issue by ghost** [sven15/dapscompare#21]
My case involved a little over 50 changed images, navigating between them via [Previous]/[Next] proved a bit arduous, because each seems to load for about a second. It does not seem to matter whether an image had previously been opened.

[This is with the 0.2.0 version, not the most recent 0.2.1 because that had some showstopping issues which I did not bother to investigate too much.]

**Comment by svenseeberg** [comment]
Well, the red boxes are calculated on runtime of the GUI. This takes a couple of seconds, depending on the amount of changed pixels. The only way to solve this is offloading the calculation into a different thread.

**Comment by svenseeberg** [comment]
... and throwing the image calculation into a thread brings all sorts of mains. At least with callbacks. This needs queues and then only the newest item in a queue should be used, the others should be trashed.
