### ISSUE TITLE
dapscompare collects all output files it can find, not only those which are relevant

### ISSUE THREAD

**Issue by ghost** [sven15/dapscompare#7]
After looking through my output, I was quite confused to find the DAPS User Guide among my test case reference files. While I had used that as a basis, I had removed it from the xml directory entirely...
Finally, I realized that I had not deleted my build directory since starting out with the DAPS User Guide.

Then, I looked into the code and dapscompare creates reference images using this path:
```
build/*/*.pdf
```

It would instead be better if it checked the output of DAPS which should tell it the exact path to look at.

**Comment by svenseeberg** [comment]
I think the easiest way would be deleting the build directory before each run. we want to test the full chain anyways. I don't want to parse the daps output.

**Comment by ghost** [comment]
Actually, there is not much parsing involved, as DAPS should create a message mentioning only the file name when run as a script. Take the output, and check that it is a file (for PDF) or a directory (for HTML).

However, I see the point that we might want to test the full DAPS chain. -> Not reopening.

<sub>(Why am I writing this? Ugh./)</sub>
